server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/clientes_db
    username: spring_user
    password: dbclientes
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: mauricio@marsconsulting.com.br
    password: lnjcrjejazwpoblp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

camunda:
  bpm:
    database:
      type: postgres
    datasource:
      url: jdbc:postgresql://postgres:5432/camunda
      username: camunda
      password: camunda
      driver-class-name: org.postgresql.Driver
    admin-user:
      id: admin
      password: admin
      firstName: Administrator
    deployment-resource-pattern: classpath:/processes/*.bpmn, classpath:/processes/*.dmn
    auto-deployment-enabled: true

app:
  notifications:
    credit-request:
      recipient: mauricio@marsconsulting.com.br
